name: 02 – Workflow Events

on:
#  push:
  workflow_dispatch:
#  schedule:
#    - cron: "*/30 * * * *"


jobs:
  my-job1:
    name: My job 1
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Uruchomił mnie event - ${{github.event_name}}"
  my-job2:
    name: My job 2
    runs-on: ubuntu-latest
    steps:
      - name: Hardware
        run: | 
          echo "Wyswietl zasoby runnera!"
          lscpu
          free -h
          df -h
