name: 02 – Workflow Events

on:
#  push:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Uruchomił mnie event - ${{github.event_name}}"

