name: 03 – Runners

on:
#  push:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"


jobs:
  ubuntu-echo:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Hardware
        run: | 
          echo "Wyswietl zasoby runnera!"
          lscpu
          free -h
          df -h
  windows-echo:
    name: windows
    runs-on: windows-latest
    steps:
    - name: Show OS
      shell: bash
      run: | 
        echo "Działa na bashu."
        echo "$RUNNER_OS"
  macos-echo:
    name: macos
    runs-on: macos-latest
    steps:
      - name: Hardware
        run: | 
          echo "This job is running on a MacOS runner."
          echo "$RUNNER_OS"
  ubuntu-self-hosted:
    name: ubuntu self-hosted
    runs-on: self-hosted
    steps:
      - name: Hardware
        run: | 
          echo "Wyswietl zasoby runnera!"
          lscpu
          free -h
          df -h
          echo "Tworze pliki"
          echo "To jest plik 1" > plik1.txt
          echo "To jest plik 2" > plik2.txt
          pwd
          ls -l