name: 03 – Runners

on:
#  push:
  workflow_dispatch:
#  schedule:
#    - cron: "*/30 * * * *"


jobs:
  ubuntu-echo: # 
    name: ubuntu # nazwa joba, która będzie widoczna w UI
    runs-on: ubuntu-latest # wybieramy system operacyjny, na którym będzie działał runner (chmurowy)
    steps: # kroki, które będą wykonywane na runnerze
      - name: Hardware # nazwa kroku, która będzie widoczna w UI
        run: | # polecenia, które będą wykonane na runnerze
          echo "Wyswietl zasoby runnera!"
          lscpu
          free -h
          df -h
  windows-echo: # nazwa joba, która będzie widoczna w UI
    name: windows # nazwa joba, która będzie widoczna w UI
    runs-on: windows-latest # wybieramy system operacyjny, na którym będzie działał runner (chmurowy)
    steps:
    - name: Show OS # nazwa kroku, która będzie widoczna w UI
      shell: bash # domyślnie na Windows runnerze jest to powershell, ale możemy to zmienić
      run: | 
        echo "Działa na bashu."
        echo "$RUNNER_OS"
  macos-echo:
    name: macos
    runs-on: macos-latest
    steps:
      - name: Hardware
        run: | 
          echo "This job is running on a MacOS runner."
          echo "$RUNNER_OS"
  ubuntu-self-hosted: # nazwa joba, która będzie widoczna w UI
    name: ubuntu self-hosted # nazwa joba, która będzie widoczna w UI
    runs-on: self-hosted # używamy własnego runnera, który zarejestrowaliśmy wcześniej (na maszynie lokalnej)
    steps:
      - name: Hardware
        run: | 
          echo "Wyswietl zasoby runnera!"
          lscpu
          free -h
          df -h
          echo "Tworze pliki"
          echo "To jest plik 1" > plik1.txt
          echo "To jest plik 2" > plik2.txt
          pwd
          ls -l