name: "05 – 1 – Event Filters and Activity Types"
on:
  pull_request:
    types: [opened, synchronize] # uruchmiaj gdy PR jest otwierany lub aktualizowany (push do gałęzi źródłowej - main)
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "Running whenever a PR is opened or synchronized AND base branch is main."