name: 14-01-start-build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo "To jest mój przekazany artefakt" > output.txt

      - name: Sleep
        run: sleep 30

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output.txt
