name: 01 - Build Blocks

on:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed Step
        run: |
          echo "I will fail now"
          exit 1
      - name: Say Goodbye
        run: |
          echo "This step will be skipped if the previous step fails"