name: 01 - Build Blocks v1.1

on:
  push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Tworze pliki
        run: |
          echo "To jest plik 1" > plik1.txt
          echo "To jest plik 2" > plik2.txt
      - name: Wyswietlam pliki w katalogu
        run: | 
          ls -la
      - name: Otwieram pliki
        run: |
          cat plik1.txt
          cat plik2.txt
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed Step
        run: |
          echo "I will fail now"
          exit 0
      - name: Say Goodbye
        run: |
          echo "This step will be skipped if the previous step fails"